#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    echo "You can't run this app from the web, only CLI is allowed";
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Povils\Figlet\Figlet;

$figlet = new Figlet();

$figlet
    ->setFont('big')
    ->setFontColor('red');
    //->setBackgroundColor('blue');

$signature = $figlet->render('Themeboot'). 'Usage:  themeboot help (to view available commands).     '. 'themeboot init (from project directory. If running from Themes Directory, make sure to provide the `themeDir` parameter for the project Directory)';

$app = new App([
    'app_path' => __DIR__ . '/app/Command'
]);
$app->setSignature($signature);

$app->runCommand($argv);
